services:
  - type: web
    name: videojet-maroc-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
